### ISSUE TITLE
Can't get this to work for me.

### ISSUE THREAD

**Issue by imjoeybrennan** [shaekuronen/jquery.flexloader#2]
This plugin is exactly what I was looking for!!! I'm so stoked cause I had picturefill and flexslider already set up and working, but I wanted lazyload too and stumbled upon this, so thank you for making it ;)

My issue is that after setting it all up im just pulling the 1x1.gif everywhere. Here is an example of my HTML

```
<div class="flexslider">
    <ul class="slides">
        <li class="slide slide-01">
            <span data-picture>
                <span 
                    data-src="images/1x1.gif"
                    data-original="images/small/strap-logo_small.jpg">
                </span>
                <span 
                    data-src="images/1x1.gif"
                    data-original="images/small/strap-logo_small.jpg"
                    data-media="(max-width: 400px)">
                </span>
                <span
                    data-src="images/1x1.gif"
                    data-original="images/strap-logo.jpg"
                    data-media="(min-width: 400px)">
                </span>
                <noscript>
                    <img src="images/strap-logo.jpg" />
                </noscript>
                </span>
            </span>
        </li>
    </ul>
</div>
```

The JS for flexslider-init.js looks like

```
$(window).load(function() {
    $('.flexslider').flexslider({
        animation: "fade",
        slideshow: true,
        animationLoop: true,
        controlNav: false,
        directionNav: true,
        prevText: "",
        nextText: "",
        start: function(slider) {
            $.flexloader(slider, {
                'picturefill': true
            });
        },
        after: function(slider) {
            $.flexloader(slider, {
                'picturefill': true
            });
        }
    });
});
```

Other libraries I'm using are 
jquery.scrollTo.min.js

jquery.videoBG.min.js

jquery.isotope.min.js
jquery.isotope.sloppy-masonry.min.js
jquery.isotope-init.min.js

jquery.fitvids.min.js
jquery.fitvids-init.min.js

jquery.flexloader.js
jquery.flexslider.min.js
jquery.flexslider-init.min.js

external/matchmedia.js
picturefill.js

Any help would be great! Thanks!

**Comment by shaekuronen** [comment]
Thanks!

Hmm, your implementation looks good, can you post a link?

**Comment by imjoeybrennan** [comment]
Figured it out. I was using jQuery 1.8.3 and so once I switched to the latest it all worked out. Maybe this is an opportunity to find where it looses jQuery support and even create some fallbacks or adjustments so it really supports older versions :D

Thanks again for this awesome plugin!
