### ISSUE TITLE
First slide has 1px height when Flexslider's smoothHeight option is enabled

### ISSUE THREAD

**Issue by kevinsmith** [shaekuronen/jquery.flexloader#4]
If Flexslider's smoothHeight option is enabled and Flexloader is being used, the first slide will display with a height of 1px. Any kind of click will cause Flexslider to resize the slider appropriately, and all but the first slide work fine. It's just that first slide.

I'm happy to help troubleshoot and fix it. Just not sure where to start with this one.

**Comment by kevinsmith** [comment]
For anyone else that finds this bug report, you can temporarily get around the issue by loading the first slide as you ordinarily would without Flexloader.

**Comment by kevinsmith** [comment]
Hmm, looks like it also happens if the user clicks far enough ahead in the slider that the image in question hasn't been loaded by Flexloader yet.

**Comment by shaekuronen** [comment]
Hi Kevin thanks for the feedback!  Do you have an example online of this issue?

**Comment by kevinsmith** [comment]
Well, after trying to get you a trimmed-down example, I discovered it was all because I put `width: auto;` on the `img` element. Take that out, and everything's fine. Weird.

Sorry for the bother!

**Comment by shaekuronen** [comment]
Good to know, thanks for the heads up!
