### ISSUE TITLE
The slider loads all the resources on page load - shouldn't it lasy-load them, as needed?

### ISSUE THREAD

**Issue by erosnicolau** [shaekuronen/jquery.flexloader#8]
Hello,
Looking into the NAV section of the FireBug, I noticed that ALL the image resources are loaded up-front, not lasy-loaded, as described ("On Flexslider start, Flexloader will update the img src of Slides 1, c1, 2, 16, & c16 ("c" prefix indicates cloned slide). When the next slide is animated to, Flexloader will update the img src of Slide 3. Slides 1, c1, & 2 are already loaded and will not updated.")
Is this a bug, or is it intended to work that way?
Eros

**Comment by shaekuronen** [comment]
What is the link to what you're looking at?

**Comment by erosnicolau** [comment]
You can check it out here:
http://lab.hbfx.ro/e/demo2/
But your demo version does the same (loads all the slices up front, not gradually as needed)

**Comment by shaekuronen** [comment]
Have you created a demo without the Flexslider sync option? Checked [demo](http://shaekuronen.github.io/jquery.flexloader/#flexloader-demo-3) and the Flexloader + Picturefill demo is loading images as expected.

**Comment by erosnicolau** [comment]
Well isn't Firefox a sweetheart... This evening your code pre-loads as it should... Sorry for this, please close or delete this issue.

**Comment by shaekuronen** [comment]
Awesome, glad it worked out, happy coding!
